//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 
namespace ABC.Workspaces.Windows.Settings.ApplicationBehavior {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://whatheco.de/abc/workspaces/windows/ApplicationBehaviors")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://whatheco.de/abc/workspaces/windows/ApplicationBehaviors", IsNullable=false)]
    public partial class ApplicationBehaviors {
        
        private WindowList commonIgnoreWindowsField;
        
        private ApplicationBehaviorsProcess[] processField;
        
        private string guidField;
        
        /// <remarks/>
        public WindowList CommonIgnoreWindows {
            get {
                return this.commonIgnoreWindowsField;
            }
            set {
                this.commonIgnoreWindowsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Process")]
        public ApplicationBehaviorsProcess[] Process {
            get {
                return this.processField;
            }
            set {
                this.processField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Guid {
            get {
                return this.guidField;
            }
            set {
                this.guidField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://whatheco.de/abc/workspaces/windows/ApplicationBehaviors")]
    public partial class WindowList {
        
        private Window[] windowField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Window")]
        public Window[] Window {
            get {
                return this.windowField;
            }
            set {
                this.windowField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://whatheco.de/abc/workspaces/windows/ApplicationBehaviors")]
    public partial class Window {
        
        private string classNameField;
        
        private string titleField;
        
        private WindowVisible visibleField;
        
        public Window() {
            this.visibleField = WindowVisible.Both;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ClassName {
            get {
                return this.classNameField;
            }
            set {
                this.classNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(WindowVisible.Both)]
        public WindowVisible Visible {
            get {
                return this.visibleField;
            }
            set {
                this.visibleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://whatheco.de/abc/workspaces/windows/ApplicationBehaviors")]
    public enum WindowVisible {
        
        /// <remarks/>
        True,
        
        /// <remarks/>
        False,
        
        /// <remarks/>
        Both,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://whatheco.de/abc/workspaces/windows/ApplicationBehaviors")]
    public partial class ApplicationBehaviorsProcess {
        
        private ApplicationBehaviorsProcessIgnoreWindows ignoreWindowsField;
        
        private ApplicationBehaviorsProcessHideBehavior hideBehaviorField;
        
        private string nameField;
        
        private string companyNameField;
        
        private string versionField;
        
        /// <remarks/>
        public ApplicationBehaviorsProcessIgnoreWindows IgnoreWindows {
            get {
                return this.ignoreWindowsField;
            }
            set {
                this.ignoreWindowsField = value;
            }
        }
        
        /// <remarks/>
        public ApplicationBehaviorsProcessHideBehavior HideBehavior {
            get {
                return this.hideBehaviorField;
            }
            set {
                this.hideBehaviorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CompanyName {
            get {
                return this.companyNameField;
            }
            set {
                this.companyNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://whatheco.de/abc/workspaces/windows/ApplicationBehaviors")]
    public partial class ApplicationBehaviorsProcessIgnoreWindows : WindowList {
        
        private ApplicationBehaviorsProcessIgnoreWindowsMode modeField;
        
        public ApplicationBehaviorsProcessIgnoreWindows() {
            this.modeField = ApplicationBehaviorsProcessIgnoreWindowsMode.NoneExcept;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(ApplicationBehaviorsProcessIgnoreWindowsMode.NoneExcept)]
        public ApplicationBehaviorsProcessIgnoreWindowsMode Mode {
            get {
                return this.modeField;
            }
            set {
                this.modeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://whatheco.de/abc/workspaces/windows/ApplicationBehaviors")]
    public enum ApplicationBehaviorsProcessIgnoreWindowsMode {
        
        /// <remarks/>
        AllExcept,
        
        /// <remarks/>
        NoneExcept,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://whatheco.de/abc/workspaces/windows/ApplicationBehaviors")]
    public partial class ApplicationBehaviorsProcessHideBehavior {
        
        private object[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Default", typeof(ApplicationBehaviorsProcessHideBehaviorDefault))]
        [System.Xml.Serialization.XmlElementAttribute("Include", typeof(ApplicationBehaviorsProcessHideBehaviorInclude))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://whatheco.de/abc/workspaces/windows/ApplicationBehaviors")]
    public partial class ApplicationBehaviorsProcessHideBehaviorDefault {
        
        private ApplicationBehaviorsProcessHideBehaviorDefaultHide hideField;
        
        private ConsiderWindows considerWindowsField;
        
        public ApplicationBehaviorsProcessHideBehaviorDefault() {
            this.considerWindowsField = ConsiderWindows.CurrentDesktopWindowsOnly;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ApplicationBehaviorsProcessHideBehaviorDefaultHide Hide {
            get {
                return this.hideField;
            }
            set {
                this.hideField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(ConsiderWindows.CurrentDesktopWindowsOnly)]
        public ConsiderWindows ConsiderWindows {
            get {
                return this.considerWindowsField;
            }
            set {
                this.considerWindowsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://whatheco.de/abc/workspaces/windows/ApplicationBehaviors")]
    public enum ApplicationBehaviorsProcessHideBehaviorDefaultHide {
        
        /// <remarks/>
        SelectedWindow,
        
        /// <remarks/>
        AllProcessWindows,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://whatheco.de/abc/workspaces/windows/ApplicationBehaviors")]
    public enum ConsiderWindows {
        
        /// <remarks/>
        AllWindows,
        
        /// <remarks/>
        CurrentDesktopWindowsOnly,
        
        /// <remarks/>
        AllDesktopWindows,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://whatheco.de/abc/workspaces/windows/ApplicationBehaviors")]
    public partial class ApplicationBehaviorsProcessHideBehaviorInclude : WindowList {
        
        private ConsiderWindows considerWindowsField;
        
        public ApplicationBehaviorsProcessHideBehaviorInclude() {
            this.considerWindowsField = ConsiderWindows.CurrentDesktopWindowsOnly;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(ConsiderWindows.CurrentDesktopWindowsOnly)]
        public ConsiderWindows ConsiderWindows {
            get {
                return this.considerWindowsField;
            }
            set {
                this.considerWindowsField = value;
            }
        }
    }
}
