//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 
namespace ABC.Workspaces.Windows.Settings.ProcessBehavior {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://whatodo.at/whathecode/vdm-api/ProcessBehaviors")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://whatodo.at/whathecode/vdm-api/ProcessBehaviors", IsNullable=false)]
    public partial class ProcessBehaviors {
        
        private WindowList commonIgnoreWindowsField;
        
        private ProcessBehaviorsProcess[] processField;
        
        /// <remarks/>
        public WindowList CommonIgnoreWindows {
            get {
                return this.commonIgnoreWindowsField;
            }
            set {
                this.commonIgnoreWindowsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Process")]
        public ProcessBehaviorsProcess[] Process {
            get {
                return this.processField;
            }
            set {
                this.processField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://whatodo.at/whathecode/vdm-api/ProcessBehaviors")]
    public partial class WindowList {
        
        private Window[] windowField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Window")]
        public Window[] Window {
            get {
                return this.windowField;
            }
            set {
                this.windowField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://whatodo.at/whathecode/vdm-api/ProcessBehaviors")]
    public partial class Window {
        
        private string classNameField;
        
        private string titleField;
        
        private WindowVisible visibleField;
        
        public Window() {
            this.visibleField = WindowVisible.Both;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ClassName {
            get {
                return this.classNameField;
            }
            set {
                this.classNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(WindowVisible.Both)]
        public WindowVisible Visible {
            get {
                return this.visibleField;
            }
            set {
                this.visibleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://whatodo.at/whathecode/vdm-api/ProcessBehaviors")]
    public enum WindowVisible {
        
        /// <remarks/>
        True,
        
        /// <remarks/>
        False,
        
        /// <remarks/>
        Both,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://whatodo.at/whathecode/vdm-api/ProcessBehaviors")]
    public partial class ProcessBehaviorsProcess {
        
        private ProcessBehaviorsProcessIgnoreWindows ignoreWindowsField;
        
        private ProcessBehaviorsProcessHideBehavior hideBehaviorField;
        
        private string targetProcessNameField;
        
        private string targetProcessCompanyNameField;
        
        private string targetProcessVersionField;
        
        private string guidField;
        
        private string versionField;
        
        /// <remarks/>
        public ProcessBehaviorsProcessIgnoreWindows IgnoreWindows {
            get {
                return this.ignoreWindowsField;
            }
            set {
                this.ignoreWindowsField = value;
            }
        }
        
        /// <remarks/>
        public ProcessBehaviorsProcessHideBehavior HideBehavior {
            get {
                return this.hideBehaviorField;
            }
            set {
                this.hideBehaviorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TargetProcessName {
            get {
                return this.targetProcessNameField;
            }
            set {
                this.targetProcessNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TargetProcessCompanyName {
            get {
                return this.targetProcessCompanyNameField;
            }
            set {
                this.targetProcessCompanyNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TargetProcessVersion {
            get {
                return this.targetProcessVersionField;
            }
            set {
                this.targetProcessVersionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Guid {
            get {
                return this.guidField;
            }
            set {
                this.guidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://whatodo.at/whathecode/vdm-api/ProcessBehaviors")]
    public partial class ProcessBehaviorsProcessIgnoreWindows : WindowList {
        
        private ProcessBehaviorsProcessIgnoreWindowsMode modeField;
        
        public ProcessBehaviorsProcessIgnoreWindows() {
            this.modeField = ProcessBehaviorsProcessIgnoreWindowsMode.NoneExcept;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(ProcessBehaviorsProcessIgnoreWindowsMode.NoneExcept)]
        public ProcessBehaviorsProcessIgnoreWindowsMode Mode {
            get {
                return this.modeField;
            }
            set {
                this.modeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://whatodo.at/whathecode/vdm-api/ProcessBehaviors")]
    public enum ProcessBehaviorsProcessIgnoreWindowsMode {
        
        /// <remarks/>
        AllExcept,
        
        /// <remarks/>
        NoneExcept,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://whatodo.at/whathecode/vdm-api/ProcessBehaviors")]
    public partial class ProcessBehaviorsProcessHideBehavior {
        
        private object[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Default", typeof(ProcessBehaviorsProcessHideBehaviorDefault))]
        [System.Xml.Serialization.XmlElementAttribute("Include", typeof(ProcessBehaviorsProcessHideBehaviorInclude))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://whatodo.at/whathecode/vdm-api/ProcessBehaviors")]
    public partial class ProcessBehaviorsProcessHideBehaviorDefault {
        
        private ProcessBehaviorsProcessHideBehaviorDefaultHide hideField;
        
        private ConsiderWindows considerWindowsField;
        
        public ProcessBehaviorsProcessHideBehaviorDefault() {
            this.considerWindowsField = ConsiderWindows.CurrentDesktopWindowsOnly;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ProcessBehaviorsProcessHideBehaviorDefaultHide Hide {
            get {
                return this.hideField;
            }
            set {
                this.hideField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(ConsiderWindows.CurrentDesktopWindowsOnly)]
        public ConsiderWindows ConsiderWindows {
            get {
                return this.considerWindowsField;
            }
            set {
                this.considerWindowsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://whatodo.at/whathecode/vdm-api/ProcessBehaviors")]
    public enum ProcessBehaviorsProcessHideBehaviorDefaultHide {
        
        /// <remarks/>
        SelectedWindow,
        
        /// <remarks/>
        AllProcessWindows,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://whatodo.at/whathecode/vdm-api/ProcessBehaviors")]
    public enum ConsiderWindows {
        
        /// <remarks/>
        AllWindows,
        
        /// <remarks/>
        CurrentDesktopWindowsOnly,
        
        /// <remarks/>
        AllDesktopWindows,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://whatodo.at/whathecode/vdm-api/ProcessBehaviors")]
    public partial class ProcessBehaviorsProcessHideBehaviorInclude : WindowList {
        
        private ConsiderWindows considerWindowsField;
        
        public ProcessBehaviorsProcessHideBehaviorInclude() {
            this.considerWindowsField = ConsiderWindows.CurrentDesktopWindowsOnly;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(ConsiderWindows.CurrentDesktopWindowsOnly)]
        public ConsiderWindows ConsiderWindows {
            get {
                return this.considerWindowsField;
            }
            set {
                this.considerWindowsField = value;
            }
        }
    }
}
